---
driver:
  name: ec2
  aws_access_key_id: <%= ENV['ARTIFACTS_AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key: <%= ENV['ARTIFACTS_AWS_SECRET_ACCESS_KEY'] %>
  aws_ssh_key_id: <%= ENV['AWS_KEYPAIR_NAME'] %>
  ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>
  security_group_ids: ["default"]
  security_group_ids: default
  require_chef_omnibus: "11.12.8"
  tags:
    "created-by": "test-kitchen"

use_vagrant_berkshelf_plugin: true

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
    driver:
      image_id: ami-967edcff
      username: ubuntu
      flavor_id: "m1.small"
      tags:
        Name: cookbook-qubell-build-ct-Ubuntu-12.04
        owner_name: test-kitchen

  - name: ubuntu-10.04
    driver:
      image_id: ami-9f3906f6
      username: ubuntu
      flavor_id: "m1.small"
      tags:
        Name: cookbook-qubell-build-ct-Ubuntu-10.04
        owner_name: test-kitchen

  - name: centos-6.4
    driver:
      image_id: ami-bf5021d6
      username: root
      flavor_id: "m1.small"
      tags:
        Name: cookbook-qubell-build-ct-CentOS-6.4
        owner_name: test-kitchen

  - name: centos-5.3
    driver:
      image_id: ami-beda31d7
      username: root
      flavor_id: "m1.small"
      tags:
        Name: cookbook-qubell-build-ct-CentOS-5.3
        owner_name: test-kitchen

suites:
  - name: default
    run_list:
      - recipe[minitest-handler]
      - recipe[cookbook-qubell-build_test]
    attributes: {"cookbook-qubell-build": {
                  "port": 8080,
                  "dest_path": "/tmp", 
                  "target": "/tmp/mvn"
                  },
                 "scm": {
                   provider: "git",
                   repository: "git://github.com/qubell/starter-java-web.git",
                   revision: "HEAD"
                 },
                }
